# Tidy

`r newthought("The **ggplot2** framework is a")` very efficient and powerful 
framework for 
creating visualizations. This comes in part from the fact that it sticks
to a specific data format for its input. It requires you to start with 
data in a what's called a "tidy" format. 

In the previous section, I used an example dataset that was already in this
format, to make it easier for you to get started with plotting. However, 
to leverage the power of **ggplot2** for real datasets, you have to know 
how to get them into this tidy format. This section will explain this format,
as well as how you can clean real datasets to convert them into this format. 

## Tidy format

`r newthought("When you hear the term")` "tidy data", you might just think of a "clean" 
dataset---one where unneeded columns have been removed, for example, and
perhaps that's in a nice **rectangular format**.^[**rectangular format.** A data format 
where each column has data in the same class (e.g., date, number) and is the 
same length. (Think of the format of data in a table of a paper, or in a clean 
Excel spreadsheet.]

[More about tidy data]

## Tidyverse tools

`r newthought("As an epidemiologist,")` I meet many people who learned SAS as students 
and continue
to use it. A common misperception is that R is good for visualizations, but bad for
cleaning data. While in the past this might have been (somewhat) valid, now it couldn't 
be further from the truth. With a collection of tools available through the 
**tidyverse**,^[**tidyverse.** A collection of packages to work with data in a 
"tidy" format, or to convert it to that format if needed. Many of these packages 
are developed and maintained by people at RStudio. If you run `library("tidyverse")`,
you can load the core tidyverse packages in your R session. This way, you avoid
having to load them one by one.] 
you can write clean and compact code to clean even very large and 
messy datasets.

This collection of tools follows the principle that hard problems can be best solved
by small tools that can be combined together, very much in-line with the **Unix
philosophy**. 

The tidyverse works as well as it does because, for many parts of it, it requires
a common input and output, and those input and output specifications are 
identical (the tidy data format).
If you want to get a better idea of this concept, and why it's so powerful, 
think of some of the
classic toys, like Legos (train sets and Lincoln logs also
work here). Each piece takes the same input and produces the same output. Think of 
the bottom of a Lego---it "inputs" small, regularly-spaced pegs, which are exactly
what's at the top ("output") of each Lego block. This common input and output 
means that the blocks can be joined together in an extraordinary number of 
different combinations, and that you can imagine and then make very complex 
structures with the blocks. 

## Subsetting

### Selecting columns

### Slicing rows

### Filtering rows

## Adding 

## Summarizing

## Reformatting